name: DungeonKey
author: Alec Diaz
version: 1.0.0
main: me.alec.dungeonkey.DungeonKey
description: Key to teleport players to dungeon
api-version: 1.15
commands:
  dungeonkey:
    usage: /dungeonkey
    aliases: [dk]