# List of materials https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
globals:
  # For use in testing
  dropRate: 50
#  dropRate: .5
keys:
  iceDungeon:
    world: builderworld
    coordinates:
      x: 41.0
      y: 80.0
      z: -323
      yaw: 0
      pitch: 0
    material: SKELETON_SKULL
    displayName: Ice Dungeon Key
    item-lore: Right click to teleport to the Ice Dungeon!
    dropRate: 0.5
    reset-block-coordinates:
      x: 41
      y: 80
      z: -500
  endDungeon:
    world: builderworld
    coordinates:
      x: 188.0
      y: 41.0
      z: -254
      yaw: 90
      pitch: 0
    material: ZOMBIE_HEAD
    displayName: End Dungeon Key
    item-lore: Right click to teleport to the End Dungeon!
    dropRate: 0.3
  waterDungeon:
    world: builderworld
    coordinates:
      x: 188.0
      y: 41.0
      z: -254
      yaw: 0
      pitch: 0
    material: CREEPER_HEAD
    displayName: Water Dungeon Key
    item-lore: Right click to teleport to the Water Dungeon!
    dropRate: 0.3
# Use no punctuation on bosses
# ex. Mad Scientist -> madscientist
exitKey:
  world: builderworld
  coordinates:
    x: 220.0
    y: 152.0
    z: -577.0
    yaw: 90
    pitch: 0
  material: ZOMBIE_HEAD
  displayName: Exit Key
  item-lore: Right click to teleport back to spawn!
bosses:
  - madscientist
